---
abstract: 'Run CGIs in Catalyst'
author:
  - 'Matt S. Trout <mst@shadowcat.co.uk>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Controller-WrapCGI
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.7007
  Class::C3: 0
  File::Find::Rule: 0
  File::Slurp: 0
  HTTP::Request::AsCGI: 0
  List::MoreUtils: 0
  Task::Weaken: 0
  URI: 0
  parent: 0
version: 0.0023
